# ml_pipeline/reporting.py

"""
Turn reports/*.json into prose: the README results block and reports/EVALUATION.md.

Nothing here computes a metric. Every number is read from a report written by a
pipeline script; a report that does not exist renders as "pending", never as a guess.
The output is deterministic for a given set of reports, so CI can check that the README
and EVALUATION.md are up to date (`--check`).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.core.settings import get_settings

REPORTS = ("data_quality", "model_comparison", "upskilling_eval", "salary_eval", "workforce_summary",
           "multilingual_eval", "impact")
START, END = "<!-- results:start -->", "<!-- results:end -->"
STATUS_START, STATUS_END = "<!-- evidence-status:start -->", "<!-- evidence-status:end -->"
MODEL_ORDER = ("b0", "b1", "b2", "b3a", "b3b", "hgt")


def load_reports(reports_dir: Path | None = None) -> dict[str, dict | None]:
    d = reports_dir or get_settings().reports_dir
    out: dict[str, dict | None] = {}
    for name in REPORTS:
        p = d / f"{name}.json"
        out[name] = json.loads(p.read_text(encoding="utf-8")) if p.exists() else None
    return out


# --- formatting ---------------------------------------------------------------------------------

def num(x: Any, digits: int = 0) -> str:
    if x is None:
        return "-"
    return f"{x:,.{digits}f}"


def pct(x: Any, digits: int = 1) -> str:
    return "-" if x is None else f"{x * 100:.{digits}f}%"


def inr(x: Any) -> str:
    if x is None:
        return "-"
    x = float(x)
    if x >= 1e7:
        return f"₹{x / 1e7:.2f} Cr"
    if x >= 1e5:
        return f"₹{x / 1e5:.2f} L"
    return f"₹{x:,.0f}"


def ci(v: Any, digits: int = 3) -> str:
    if not v:
        return ""
    return f" [{v[0]:.{digits}f}, {v[1]:.{digits}f}]"


def table(header: list[str], rows: list[list[str]], align: str | None = None) -> str:
    align = align or "l" + "r" * (len(header) - 1)
    sep = ["---:" if a == "r" else "---" for a in align]
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep) + " |"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def pending(what: str) -> str:
    return f"*Pending:* {what}"


def _stamp(rep: dict | None) -> str:
    if not rep:
        return ""
    p = rep.get("provenance", {})
    git = p.get("git", {})
    commit = (git.get("commit") or "")[:7]
    dirty = " (uncommitted changes)" if git.get("dirty") else ""
    return f"<sub>Generated by `{p.get('script', '?')}` at {p.get('generated_at_utc', '?')} from commit `{commit}`{dirty}.</sub>"


# --- sections -----------------------------------------------------------------------------------

def data_section(dq: dict | None, short: bool = True) -> str:
    title = "### Data (from `reports/data_quality.json`)"
    if not dq:
        return f"{title}\n\n" + pending("cleaning, geography, ESCO linking and NCO mapping statistics.")
    counts = {r["step"]: r["rows"] for r in dq.get("row_counts", []) if isinstance(r, dict) and "step" in r}
    geo, sl, tl, sal, tmp = dq["geography"], dq["skill_linking"], dq["title_linking"], dq["salary"], dq["temporal"]
    tiers = geo.get("jobs_by_primary_tier", {})

    def tier(k: str) -> int | None:
        for key in (k, f"{k}.0"):
            if key in tiers:
                return tiers[key]
        return None

    by_tier = sal.get("by_tier", {})
    gold = dq.get("gold_evaluation", {}).get("skills", {})
    if gold.get("status") == "evaluated":
        gold_txt = (f"{pct(gold['precision_mention_weighted'])}{_ci_pct(gold.get('precision_mention_weighted_ci95'))}"
                    f" precision, {pct(gold.get('recall_mention_weighted'))} recall "
                    f"(mention-weighted, {gold['labelled_test']} held-out labels)")
    else:
        gold_txt = "*pending team labels*"
    rows = [
        ["Raw postings", num(dq["dataset"]["raw_rows"])],
        ["After removing duplicate job IDs", num(dq["final_jobs"])],
    ]
    if "jobs_with_tags" in counts:
        rows.append(["Jobs with at least one skill tag", num(counts["jobs_with_tags"])])
    rows += [
        ["Non-remote jobs resolved to an Indian city",
         f"{pct(geo['city_resolution_rate_excl_remote'])} ({num(geo['distinct_cities'])} cities, "
         f"{geo['distinct_states']} states/UTs)"],
        ["Jobs by primary city tier (1 / 2 / 3)", f"{num(tier('1'))} / {num(tier('2'))} / {num(tier('3'))}"],
        ["Unique skill tags", f"{num(sl['unique_tags'])} ({num(sl['tag_mentions'] / 1000)}K mentions)"],
        ["Tag mentions linked to an ESCO skill", f"{pct(sl['mention_coverage'])} (threshold {sl['threshold']}, "
         f"{'tuned on gold labels' if str(sl.get('threshold_status', '')).startswith('tuned') else 'provisional'})"],
        ["Jobs linked to an ESCO occupation",
         f"{pct(tl['job_coverage'])} ({num(tl['distinct_occupations_used'])} distinct occupations)"],
        ["Postings that disclose salary",
         f"{pct(sal['disclosed_share'])} (Tier 1: {pct(by_tier.get('1', {}).get('salary_disclosed_share'))}, "
         f"Tier 2: {pct(by_tier.get('2', {}).get('salary_disclosed_share'))}, "
         f"Tier 3: {pct(by_tier.get('3', {}).get('salary_disclosed_share'))})"],
        ["Posting dates", f"{'real, from `jobId`' if tmp.get('posting_dates_available') else 'not available'}; "
         f"{pct(tmp.get('share_consistent_within_1_day'))} agree with \"N days ago\"; "
         f"inferred scrape date {tmp.get('inferred_scrape_date')}"],
        ["Skill-linking precision (team-labelled gold)", gold_txt],
    ]
    out = f"{title}\n\n" + table(["", ""], rows, "lr")
    if not short:
        out += "\n\n" + _stamp(dq)
    return out


def _ci_pct(v: Any) -> str:
    return f" [{v[0] * 100:.1f}, {v[1] * 100:.1f}]" if v else ""


def _models(mc: dict) -> list[tuple[str, dict]]:
    ms = mc.get("models", {})
    return [(k, ms[k]) for k in MODEL_ORDER if k in ms] + [(k, v) for k, v in ms.items() if k not in MODEL_ORDER]


def models_section(mc: dict | None, short: bool = True) -> str:
    title = "### Models (from `reports/model_comparison.json`)"
    if not mc:
        return f"{title}\n\n" + pending(
            "T1 job-skill completion, T2 occupation-skill recovery and T3 candidate→job fit for B0 Popularity, "
            "B1 TF-IDF kNN, B2 SkillAlign (mpnet + FAISS), B3a Adamic-Adar, B3b LightGCN and the HGT.")
    rows = []
    for _, m in _models(mc):
        mean = m["mean"]

        def cell(task: str, key: str, _mean=mean) -> str:
            t = _mean.get(task)
            if not t:
                return "n/a"
            return f"{t[key]:.3f}" + ("" if short else ci(t.get(f"{key}_ci95")))

        lat = mean.get("latency", {}).get("jobs_for_profile", {})
        rows.append([m["name"], cell("t1", "ndcg@10"), cell("t2", "ndcg@10"), cell("t3", "recall@10"),
                     cell("t3", "ndcg@10"), cell("t3", "mrr"), num(lat.get("p50_ms"), 1), num(lat.get("p95_ms"), 1),
                     num(mean.get("memory", {}).get("rss_mb"))])
    header = ["Model", "T1 NDCG@10", "T2 NDCG@10", "T3 Recall@10", "T3 NDCG@10", "T3 MRR", "p50 ms", "p95 ms", "RSS MB"]
    comp = mc.get("comparison", {})
    lines = [title, "", table(header, rows)]
    if mc.get("quick_mode"):
        lines += ["", "> Quick mode (subsampled queries): a smoke test, not the final benchmark."]
    if comp:
        lines += ["", f"**Shipped:** {comp.get('winner_name')} ({comp.get('rule')})."]
        hv = comp.get("hgt_vs_best_baseline")
        if hv and "t3" in hv:
            d = hv["t3"]
            verdict = "beats" if comp.get("hgt_beats_best_baseline_on_t3") else "does not beat"
            lines.append(f"The HGT {verdict} the best baseline ({hv['baseline']}) on T3: paired NDCG@10 difference "
                         f"{d['mean_diff']:+.4f}{ci(d.get('ci95'), 4)}.")
    lines += ["", "T1 = hidden half of a held-out job's skills; T2 = hidden 20% of an ESCO occupation's skills; "
                  "T3 = rank ~9.5K unseen pool jobs for a pseudo-candidate. Latency = ranking all pool jobs for one profile."]
    if not short:
        lines += ["", _stamp(mc)]
    return "\n".join(lines)


def upskilling_section(ue: dict | None, short: bool = True) -> str:
    title = "### Upskilling (from `reports/upskilling_eval.json`)"
    if not ue:
        return f"{title}\n\n" + pending(
            "jobs unlocked by lazy greedy, greedy on F and top-k-by-frequency against the exact optimum, "
            "for k ∈ {1, 3, 5} and τ ∈ {0.4, 0.6, 0.8}.")
    grid = ue["grid"]
    keys = ["k=3,tau=0.6"] if short else list(grid)
    names = {"exact_ilp": "Exact (CP-SAT ILP)", "greedy_F": "Greedy on F (shipped with ILP)",
             "lazy_greedy_G": "Lazy greedy on G (1−1/e on G)", "frequency": "Top-k by frequency"}
    out = [title, ""]
    for key in keys:
        g = grid[key]
        rows = []
        for m in ("exact_ilp", "greedy_F", "lazy_greedy_G", "frequency"):
            s = g[m]
            rows.append([names[m], num(s["mean_F"], 2), f"{s['mean_gap_pct']:.2f}%", f"{s['p95_gap_pct']:.2f}%",
                         pct(s["share_optimal"]), num(s["runtime_ms_p50"], 1), num(s["runtime_ms_p95"], 1)])
        k, tau = key.replace("k=", "").split(",tau=")
        out += [f"**k = {k}, τ = {tau}** ({g['instances']} instances; mean optimum {g['mean_optimum']} postings; "
                f"ILP proven optimal in {pct(g['ilp_proven_optimal_share'])})", "",
                table(["Method", "Postings unlocked", "Mean gap", "p95 gap", "Optimal", "p50 ms", "p95 ms"], rows), ""]
    if short:
        worst = max(grid.values(), key=lambda g: g["frequency"]["mean_gap_pct"])
        out.append(f"Across all {len(grid)} (k, τ) cells, the frequency baseline's mean gap to the optimum reaches up to "
                   f"{worst['frequency']['mean_gap_pct']:.1f}%; greedy on F stays within "
                   f"{max(g['greedy_F']['mean_gap_pct'] for g in grid.values()):.2f}%. "
                   "Full grid, salary-weighted and effort-aware results: `reports/EVALUATION.md`.")
    if not short:
        bf = ue.get("ilp_vs_brute_force", {})
        if bf.get("instances_checked"):
            scope = (f" (both restricted to the same {bf['candidate_skills_per_instance']} most-listed candidate skills, "
                     f"k in {{{', '.join(map(str, bf['k_values']))}}})" if "candidate_skills_per_instance" in bf else "")
            out += [f"ILP vs brute-force enumeration{scope}: the ILP matches the enumerated optimum in "
                    f"{bf['ilp_equals_brute_force']} of {bf['instances_checked']} cases.", ""]
        else:
            out += [pending("ILP vs brute-force cross-check."), ""]
        for label, key, methods in [
            ("Salary-weighted (k = 3, τ = 0.6)", "salary_weighted_k3_tau0.6",
             ("exact_ilp", "greedy_F", "lazy_greedy_G", "frequency")),
            ("Effort-aware, budget = 3 (τ = 0.6)", "effort_aware_budget3_tau0.6",
             ("exact_ilp", "budgeted_partial", "budgeted_greedy", "frequency"))]:
            s = ue.get(key)
            if not s:
                continue
            money = "salary" in key
            rows = [[m, inr(s[m]["mean_F"]) if money else num(s[m]["mean_F"], 2), f"{s[m]['mean_gap_pct']:.2f}%",
                     pct(s[m]["share_optimal"]), num(s[m]["runtime_ms_p50"], 1)] for m in methods if m in s]
            out += [f"**{label}**" + (f": {s['effort_note']}" if "effort_note" in s else ""), "",
                    table(["Method", "Mean value", "Mean gap", "Optimal", "p50 ms"], rows), ""]
        out.append(_stamp(ue))
    return "\n".join(out).rstrip()


def salary_section(se: dict | None, short: bool = True) -> str:
    title = "### Salary (from `reports/salary_eval.json`)"
    if not se:
        return f"{title}\n\n" + pending("MAE and MdAPE of P50, interval coverage before and after conformal "
                                        "calibration, and the disclosure-bias verdict.")
    t, b, sb = se["test"], se["baseline"], se["selection_bias"]
    rows = [
        ["Model", se["model"]["type"] + " + " + se["model"]["calibration"].split(" (")[0]],
        ["Held-out postings (disclosed salary)", num(t["n"])],
        ["P50 MAE / MdAPE", f"{inr(t['mae_inr'])} / {t['mdape_pct']:.1f}%"],
        ["Baseline (ISCO sub-major × tier median) MAE / MdAPE", f"{inr(b['mae_inr'])} / {b['mdape_pct']:.1f}%"],
        ["P10-P90 coverage (target 80%): raw → calibrated", f"{pct(t['coverage_raw'])} → {pct(t['coverage_cqr'])}"],
        ["Median interval width (calibrated)", inr(t["median_width_inr_cqr"])],
        ["Disclosure predictable from job features (propensity AUC)", f"{sb['propensity']['auc']:.2f}"],
        ["Shown only when support ≥", f"{se['display_rule']['min_support']} similar disclosed postings"],
    ]
    out = f"{title}\n\n" + table(["", ""], rows, "lr")
    out += ("\n\nSalary is disclosed on only " + pct(sb["disclosed_share"]) + " of postings and disclosure is not random, "
            "so every figure is a range for *postings that disclose pay*, never a point estimate.")
    if not short:
        by = se.get("by_group", {})
        for g, label in (("tier", "City tier"), ("exp_band", "Experience band")):
            if g in by:
                rows = [[str(k), num(v["n"]), inr(v["mae_inr"]), f"{v['mdape_pct']:.1f}%", pct(v["coverage_cqr"]),
                         inr(v["median_width_inr_cqr"])] for k, v in by[g].items()]
                out += f"\n\n**By {label.lower()}**\n\n" + table(
                    [label, "n", "MAE", "MdAPE", "Coverage", "Median width"], rows)
        cat = sb.get("categorical", {})
        rows = [[k, f"{v['chi2']:,.1f}", str(v["dof"]), f"{v['cramers_v']:.3f}"] for k, v in cat.items()]
        rows += [[k, "-", "-", f"SMD {v['smd']:+.3f}, KS {v['ks_stat']:.3f}"] for k, v in sb.get("numeric", {}).items()]
        out += "\n\n**Who discloses salary**\n\n" + table(["Feature", "χ²", "dof", "Cramér's V / effect"], rows)
        out += f"\n\n{sb['propensity']['interpretation']}"
        ipw = sb.get("ipw_sensitivity", {})
        if ipw:
            out += (f"\n\nIPW sensitivity: re-weighting disclosed postings to resemble all postings moves predictions on "
                    f"undisclosed jobs by a median {ipw['median_pct_change_on_undisclosed_jobs']:+.2f}% "
                    f"(test MAE with IPW {inr(ipw['test_mae_inr_ipw'])}). {ipw.get('note', '')}")
        out += "\n\n" + _stamp(se)
    return out


def impact_section(im: dict | None, short: bool = True) -> str:
    title = "### Impact (from `reports/impact.json`)"
    if not im:
        return f"{title}\n\n" + pending("extra eligible postings for Tier-2/3 freshers from a 3-skill optimal plan "
                                        "compared with frequency advice, with every assumption listed.")
    e = im["extra_postings_vs_frequency"]
    rows = [
        ["Tier-2/3 fresher profiles (held-out, pseudo-users)", f"{num(im['users'])} (Tier 2: {im['users_by_tier']['2']}, "
         f"Tier 3: {im['users_by_tier']['3']})"],
        ["Median reachable postings: now → frequency plan → optimal plan",
         f"{num(im['eligible_before_median'])} → {num(im['eligible_after_frequency_median'])} → "
         f"{num(im['eligible_after_optimal_median'])}"],
        ["Extra postings, optimal vs frequency (mean; median [IQR])",
         f"{e['mean']:+.2f}; {e['median']:+.0f} [{e['iqr'][0]:+.0f}, {e['iqr'][1]:+.0f}]"],
        ["Profiles where the optimal plan reaches more postings", pct(im["share_users_with_more_postings"])],
        ["Profiles where it is no worse", pct(im["share_users_no_worse"])],
    ]
    out = f"{title}\n\n" + table(["", ""], rows, "lr")
    a = im["assumptions"]
    out += (f"\n\nAssumptions: k = {a['k']} skills; reachable = {a['eligibility']}; person = {a['person']}; "
            f"pool = {a['pool']}. {a['no_causal_claim'].capitalize()}.")
    if not short:
        out += f"\n\n{im['illustration']['label']} Value: {num(im['illustration']['per_1000_users_extra_reachable_postings'])}."
        out += "\n\n" + _stamp(im)
    return out


def readme_block(r: dict[str, dict | None]) -> str:
    parts = [data_section(r["data_quality"]), models_section(r["model_comparison"]),
             upskilling_section(r["upskilling_eval"]), salary_section(r["salary_eval"]), impact_section(r["impact"])]
    return "\n\n".join(parts)


def evidence_status(r: dict[str, dict | None]) -> str:
    """Which reports exist, and what run they came from. Generated so it cannot drift from reports/."""
    def link(label: str, name: str) -> str:
        return f"[{label}](reports/{name}.json)" if r[name] else label

    def state(*names: str) -> str:
        have = [n for n in names if r[n]]
        return "Available" if len(have) == len(names) else "Pending" if not have else "Partly available"

    gold = (r["data_quality"] or {}).get("gold_evaluation", {}).get("skills", {}).get("status") == "evaluated"
    ml = r["multilingual_eval"]
    ml_done = bool(ml) and any(m.get("cross_lingual", {}).get("status") == "evaluated" for m in ml["models"])
    accuracy = ("Available" if gold and ml_done else
                "Evaluation run; team labels pending" if ml else "Pending labels and evaluation")
    mc = r["model_comparison"]
    rows = [
        [link("Data quality", "data_quality"), state("data_quality"),
         "Cleaning counts, geography, linking coverage, graph counts, stage timing"],
        [link("Salary evaluation", "salary_eval"), state("salary_eval"),
         "Held-out errors, interval coverage, subgroup results, disclosure bias"],
        [link("Workforce summary", "workforce_summary"), state("workforce_summary"),
         "Field assignments, state supply coverage, shortage proxy, tier aggregates"],
        [link("Graph comparison and ablations", "model_comparison"),
         "Available (quick mode: smoke test only)" if mc and mc.get("quick_mode") else state("model_comparison"),
         "Six models on three tasks with intervals, latency and memory; names the served model" if mc
         else "No published winner or comparative latency yet"],
        [f"{link('Upskilling', 'upskilling_eval')} and {link('impact', 'impact')}", state("upskilling_eval", "impact"),
         "Gap to the exact optimum per method, runtime, and the Tier-2/3 fresher estimate with its assumptions"
         if r["upskilling_eval"] and r["impact"] else "No published real-pool optimality gap or impact estimate yet"],
        [link("Gold and multilingual accuracy", "multilingual_eval"), accuracy,
         "Linking precision and recall on team labels" if gold and ml_done
         else "Implementation exists; accuracy is not established until the team labels the frozen samples"],
    ]
    out = table(["Evidence", "Current report set", "What it establishes"], rows, "lll")
    runs = []
    for name in REPORTS:
        if r[name]:
            pv = r[name].get("provenance", {})
            git = pv.get("git", {})
            runs.append((str(pv.get("generated_at_utc", ""))[:10], (git.get("commit") or "")[:7], bool(git.get("dirty"))))
    if runs:
        days = sorted({d for d, _, _ in runs if d})
        commits = sorted({c for _, c, _ in runs if c})
        when = days[0] if len(days) == 1 else f"{days[0]} to {days[-1]}"
        out += ("\n\n**Reading the evidence:** reports record the generating script, timestamp, seed where applicable, "
                f"Git state, and supplied input hashes. The current reports were generated on {when} from "
                f"commit{'s' if len(commits) > 1 else ''} {', '.join(f'`{c}`' for c in commits)}"
                + (", with uncommitted changes in the working tree for at least one run" if any(d for _, _, d in runs) else "")
                + ". They are evidence for those runs, not proof that every later edit has been reevaluated.")
    return out


def render_readme(readme: str, r: dict[str, dict | None]) -> str:
    a, b = readme.index(START), readme.index(END)
    readme = readme[: a + len(START)] + "\n\n" + readme_block(r) + "\n\n" + readme[b:]
    if STATUS_START in readme and STATUS_END in readme:
        a, b = readme.index(STATUS_START), readme.index(STATUS_END)
        readme = readme[: a + len(STATUS_START)] + "\n\n" + evidence_status(r) + "\n\n" + readme[b:]
    return readme


# --- EVALUATION.md ------------------------------------------------------------------------------

def _linking_eval(dq: dict | None, ml: dict | None) -> str:
    out = ["## 2. Linking to ESCO", ""]
    if not dq:
        return "\n".join(out + [pending("data_quality.json")])
    sl, tl = dq["skill_linking"], dq["title_linking"]
    rows = [[str(k), pct(v["unique"]), pct(v["mentions"])] for k, v in sl.get("coverage_by_threshold", {}).items()]
    out += [f"Skills: {sl['model']}, threshold {sl['threshold']} ({sl['threshold_status']}); single-word tags must "
            "clear a stricter threshold because generic words (\"development\", \"sales\") otherwise land on unrelated "
            "ESCO skills.", "", "Coverage by threshold (share of unique tags / tag mentions linked):", "",
            table(["Threshold", "Unique tags", "Mentions"], rows), "",
            f"Titles: {pct(tl['job_coverage'])} of jobs linked to an ESCO occupation "
            f"({num(tl['distinct_occupations_used'])} occupations); skill-aware re-ranking changed "
            f"{pct(tl['rerank_changed_share'])} of links (never overriding an exact title match).", ""]
    gold = dq.get("gold_evaluation", {})
    for key, label in (("skills", "Skill links"), ("titles", "Title links")):
        g = gold.get(key, {})
        if g.get("status") == "evaluated":
            p = g.get("precision_mention_weighted", g.get("precision_weighted"))
            r_ = g.get("recall_mention_weighted", g.get("recall_weighted"))
            out.append(f"- **{label}, gold precision:** {pct(p)}{_ci_pct(g.get('precision_mention_weighted_ci95'))}, "
                       f"recall {pct(r_)} on {g.get('labelled_test')} held-out team labels ({g.get('method')}).")
        else:
            out.append(f"- **{label}, gold precision:** {g.get('status', 'pending team labels')}. The frozen stratified "
                       "sample is in `data/gold/`; the team labels it in `/admin/labelling`.")
    out += ["", "### Multilingual input", ""]
    if not ml:
        out.append(pending("reports/multilingual_eval.json"))
    else:
        for m in ml["models"]:
            en, cl = m.get("english", {}), m.get("cross_lingual", {})
            line = f"- `{m['model']}`: English "
            line += (f"precision {pct(en['precision_mention_weighted'])}, recall {pct(en['recall_mention_weighted'])}"
                     if en.get("status") == "evaluated" else en.get("status", "pending"))
            if cl.get("status") == "evaluated":
                line += "; " + "; ".join(f"{v['language']}: top-1 {pct(v['top1_accuracy'])}, recall@5 {pct(v['recall_at_5'])}"
                                         f" (n={v['n']})" for v in cl["per_language"].values())
            else:
                line += f"; cross-lingual {cl.get('status', 'pending')}"
            out.append(line)
        out += ["", f"Decision rule: {ml['decision_rule']}", "", _stamp(ml)]
    return "\n".join(out)


def _models_eval(mc: dict | None) -> str:
    out = ["## 3. Link prediction", ""]
    if not mc:
        return "\n".join(out + [pending("reports/model_comparison.json")])
    d = mc.get("data", {})
    out += ["### Protocol", "", "```", mc.get("protocol", ""), "```", "",
            "Leakage checks (asserted before any model runs): "
            f"hidden job-skill edges visible to models = {d.get('hidden_edges_in_known')}, "
            f"hidden occupation-skill edges visible = {d.get('occ_hidden_edges_in_known')}, "
            f"near-duplicate groups spanning splits = {d.get('groups_spanning_splits')}, "
            f"T3 sources all in the unseen pool = {d.get('t3_sources_all_in_pool')}. "
            f"All model selection used {num(d.get('t3_dev_queries_from_train'))} dev queries built from train jobs.", "",
            "### Results (95% bootstrap CIs; stochastic models: mean of seeds)", "",
            models_section(mc, short=False).split("\n", 2)[2], ""]
    ab = mc.get("ablations", {})
    if ab.get("without_skill_linking"):
        w = ab["without_skill_linking"]
        full = mc["models"]
        rows = [[v["name"], f"{v['t3']['ndcg@10']:.3f}",
                 f"{full[k]['mean']['t3']['ndcg@10']:.3f}" if k in full and "t3" in full[k]["mean"] else "-"]
                for k, v in w["models"].items()]
        out += ["### Ablation: does ESCO linking help?", "", w["note"], "",
                table(["Model", "T3 NDCG@10, raw tags", "T3 NDCG@10, ESCO skills"], rows), ""]
    if ab.get("hgt_variants"):
        base = mc["models"].get("hgt", {}).get("mean", {})
        rows = [["HGT (full)"] + [f"{base[t]['ndcg@10']:.3f}" if t in base else "-" for t in ("t1", "t2", "t3")]]
        rows += [[v["name"]] + [f"{v[t]['ndcg@10']:.3f}" if t in v else "-" for t in ("t1", "t2", "t3")]
                 for v in ab["hgt_variants"].values()]
        out += ["### Ablation: HGT structure (NDCG@10)", "", table(["Variant", "T1", "T2", "T3"], rows), ""]
    return "\n".join(out)


def build_evaluation(r: dict[str, dict | None]) -> str:
    dq, wf = r["data_quality"], r["workforce_summary"]
    parts = [
        "# Yojak: evaluation",
        "",
        "> Generated by `scripts/build_evaluation.py` from `reports/*.json`. Do not edit by hand: re-run "
        "`python -m ml_pipeline.evaluate_all`. Every number below comes from a report written by a script in this "
        "repository; anything not yet measured is marked *pending*.",
        "",
        "## 1. Data",
        "",
        data_section(dq, short=False).split("\n", 2)[2] if dq else pending("reports/data_quality.json"),
    ]
    if dq:
        tmp, sal = dq["temporal"], dq["salary"]
        parts += ["", f"**Time.** {tmp.get('forecasting_note', '')}", "",
                  f"**Salary units.** {sal.get('usd_note', '')} Policy: {sal.get('usd_policy')}; "
                  f"{sal.get('implausible_salary_rows')} implausible rows dropped "
                  f"(kept range {inr(sal['plausible_range_inr'][0])} to {inr(sal['plausible_range_inr'][1])}).", "",
                  f"**NCO-2015.** {dq['nco2015']['basis']}. Level: {dq['nco2015']['level']}; "
                  f"{num(dq['jobs_with_nco_family'])} jobs carry an NCO family."]
    parts += ["", _linking_eval(dq, r["multilingual_eval"]), "", _models_eval(r["model_comparison"]), "",
              "## 4. Optimal upskilling", "", "Theory: [`docs/optimality.md`](../docs/optimality.md).", "",
              upskilling_section(r["upskilling_eval"], short=False).split("\n", 2)[-1]
              if r["upskilling_eval"] else pending("reports/upskilling_eval.json"), "",
              "## 5. Salary ranges", "",
              salary_section(r["salary_eval"], short=False).split("\n", 2)[2]
              if r["salary_eval"] else pending("reports/salary_eval.json"), "",
              "## 6. Workforce planning", ""]
    if wf:
        rows = [[k, num(v)] for k, v in wf["postings_by_field"].items()]
        parts += [f"Skill families: {wf['skill_families']}. {pct(wf['share_postings_with_field'])} of postings get a field.",
                  "", table(["Field (ISCED-F broad)", "Postings"], rows), "",
                  f"Shortage index: `{wf['shortage_index_formula']}`", "",
                  table(["State", "Shortage index"], [[k, f"{v:.2f}"] for k, v in wf["top_states_by_shortage_index"].items()]),
                  "", "Caveats:", ""] + [f"- {c}" for c in wf["caveats"]] + ["", _stamp(wf)]
    else:
        parts.append(pending("reports/workforce_summary.json"))
    parts += ["", "## 7. Impact estimate", "",
              impact_section(r["impact"], short=False).split("\n", 2)[2] if r["impact"] else pending("reports/impact.json"),
              "", "## 8. Limitations", "",
              "- Naukri postings are formal-sector, English-language and urban-skewed; the informal economy is invisible here.",
              "- About two weeks of postings: no trend or forecast is claimed.",
              "- ESCO is European; many current tools (cloud platforms, frameworks) have no ESCO skill and stay as raw tags.",
              "- Eligibility (covering a share of a posting's skills) is not hiring; no outcome data exists in this dataset.",
              "- Salary is posted, not realised, and only disclosed on a non-random third of postings.",
              "- The recruiter candidate pool is SYNTHETIC and labelled as such everywhere; it demonstrates ranking, "
              "not real-candidate quality.",
              "- Supply is a state-level proxy (AISHE out-turn, PLFS youth unemployment), not field-level graduate counts.",
              "- Gold linking metrics depend on the team's labels; until labelled, thresholds are provisional.",
              ""]
    return "\n".join(parts)
