"""
Run the three demo personas end to end, without the web server.

    python scripts/demo.py                 # all personas -> reports/demo_output/
    python scripts/demo.py --only tier3-fresher

Each persona is defined in scripts/personas.yaml (illustrative people, not real users).
The script calls the same service functions the API uses, so the output is exactly what
the web app would show. It writes one JSON file per persona plus a short Markdown summary.
Needs the pipeline artifacts (python -m ml_pipeline.run_pipeline); Neo4j is not needed.
"""

import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import yaml  # noqa: E402

from app.api.schemas.yojak import PlanRequest, ProfileRequest  # noqa: E402
from app.api.services import yojak as svc  # noqa: E402
from ml_pipeline.reporting import inr  # noqa: E402

OUT = ROOT / "reports" / "demo_output"


def _salary(s: dict | None) -> str:
    if not s or not s.get("sufficient"):
        return "not enough disclosed salaries"
    return f"{inr(s['p10'])} – {inr(s['p50'])} – {inr(s['p90'])} (n={s['n_support']})"


def _labels(plan: dict) -> str:
    return ", ".join(s["skill"]["label"] for s in plan["steps"]) or "(nothing to add)"


def run_student(p: dict) -> tuple[dict, list[str]]:
    req = p["request"]
    match = svc.student_match(ProfileRequest(**req))
    plan = svc.student_plan(PlanRequest(**{**req, **p.get("plan", {})}))
    ex = match["extraction"]
    md = [f"Language detected: {ex['language'] if ex else 'n/a'}",
          "Skills understood: " + ", ".join(s["label"] for s in match["skills"]), "",
          "Top roles:"]
    md += [f"- {r['occupation_label']} ({r['postings']} postings; salary {_salary(r['salary'])})"
           for r in match["roles"][:5]]
    md += ["", "Top postings:"]
    md += [f"- {j['title']} at {j['company']}, {j['city'] or '?'} (fit {j['fit']:.0%}; {_salary(j['salary'])})"
           for j in match["jobs"][:5]]
    o, f = plan["optimal_plan"], plan["frequency_plan"]
    md += ["", f"Upskilling pool: {plan['pool']['postings']} postings (ISCO {plan['pool']['isco2']})",
           f"- Yojak plan ({o['method']}): {_labels(o)} -> eligible {o['eligible_before']} -> {o['eligible_after']}",
           f"- Most-frequent-skills plan: {_labels(f)} -> eligible {f['eligible_before']} -> {f['eligible_after']}"]
    if plan.get("effort_plan"):
        e = plan["effort_plan"]
        md.append(f"- Effort-aware plan: {_labels(e)} -> eligible {e['eligible_after']}")
    return {"match": match, "plan": plan}, md


def run_institution(p: dict) -> tuple[dict, list[str]]:
    r = p["request"]
    res = svc.institution_coverage(r["text"], [], [], r.get("isco2"), None, r.get("tiers"), r.get("states"))
    md = [f"Syllabus note: {p['syllabus_note'].strip()}",
          f"Skills found in the syllabus: {len(res['syllabus_skills'])}",
          f"Demand-weighted coverage of the top in-demand skills: {res['coverage']:.0%}", "",
          "Most-demanded skills not in the syllabus:"]
    md += [f"- {c['skill']['label']} ({c['demand_postings']} postings)" for c in res["missing_high_demand"][:8]]
    if res["low_current_demand"]:
        md += ["", "Taught, but rare in current postings:"]
        md += [f"- {c['skill']['label']} ({c['demand_postings']} postings)" for c in res["low_current_demand"][:5]]
    return res, md


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", nargs="*")
    args = ap.parse_args(argv)
    personas = yaml.safe_load((ROOT / "scripts" / "personas.yaml").read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)
    summary = ["# Yojak demo run", "",
               "> Generated by `scripts/demo.py`. The personas are illustrative (scripts/personas.yaml); "
               "every result comes from the real pipeline artifacts.", ""]
    for p in personas:
        if args.only and p["id"] not in args.only:
            continue
        t0 = time.time()
        print(f"== {p['name']}", flush=True)
        result, md = (run_institution if p["view"] == "institution" else run_student)(p)
        (OUT / f"{p['id']}.json").write_text(json.dumps({"persona": p, "result": result}, indent=2,
                                                        ensure_ascii=False, default=str), encoding="utf-8")
        summary += [f"## {p['name']}", "", p["story"].strip(), ""] + md + ["", f"<sub>{time.time() - t0:.1f} s</sub>", ""]
        print("\n".join(md), flush=True)
    (OUT / "README.md").write_text("\n".join(summary), encoding="utf-8", newline="\n")
    print(f"\nwrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
