# ml_pipeline/supply/parse.py

"""
Extract state-level supply proxies from the official PDFs into data/reference/.

  AISHE 2021-22, Table 33 (T-33)  graduate out-turn (all levels, "Grand Total") by State/UT
  PLFS 2023-24,  Table 18         unemployment rate, age 15-29, usual status (ps+ss),
                                  rural+urban, persons, by State/UT

    python -m ml_pipeline.supply.parse

Rows that cannot be read unambiguously are NOT guessed: in the AISHE PDF the West
Bengal row is fused with the All-India line, so West Bengal is written as missing.
Values in data/reference/aishe_overrides.csv (state,outturn_total,source) replace or
fill rows after a person has checked them against the printed report.
"""

from __future__ import annotations

import re
import sys

import pandas as pd
import pdfplumber

from app.core.settings import get_settings

AISHE_PAGE = 186        # 1-based page of Table 33 carrying the Grand Total columns
PLFS_PAGE = 133         # 1-based page of Table 18, age 15-29

# Source spellings -> GeoNames admin-1 names used everywhere else in Yojak.
STATE_NAMES = {
    "andaman and nicobar islands": "Andaman and Nicobar", "andaman & n. island": "Andaman and Nicobar",
    "the dadra and nagar haveli and daman and diu": "Dadra and Nagar Haveli and Daman and Diu",
    "dadra & nagar haveli & daman & diu": "Dadra and Nagar Haveli and Daman and Diu",
    "jammu & kashmir": "Jammu and Kashmir", "jammu and kashmir": "Jammu and Kashmir",
}


def canonical_state(name: str) -> str:
    n = re.sub(r"\s+", " ", name.strip())
    return STATE_NAMES.get(n.lower(), n)


def parse_aishe(pdf_path) -> pd.DataFrame:
    with pdfplumber.open(pdf_path) as pdf:
        text = pdf.pages[AISHE_PAGE - 1].extract_text() or ""
    rows, pending = [], ""
    for line in text.splitlines():
        m = re.match(r"^(\d{1,2})\s+([A-Za-z][A-Za-z &.]+?)\s+((?:\d+\s*)+)$", line.strip())
        if "India" in line:  # the fused West Bengal / All India line
            continue
        if m:
            name, nums = m.group(2), m.group(3).split()
            rows.append({"state": canonical_state(name), "outturn_total": int(nums[-1])})
        elif re.match(r"^\d{1,2}(\s+\d+)+$", line.strip()) and pending:
            rows.append({"state": canonical_state(pending), "outturn_total": int(line.split()[-1])})
            pending = ""
        elif "Dadra" in line:
            pending = "The Dadra and Nagar Haveli and Daman and Diu"
    df = pd.DataFrame(rows).drop_duplicates("state")
    df["source"] = "AISHE 2021-22 Table 33 (Grand Total), parsed from the official PDF"
    wb = pd.DataFrame([{"state": "West Bengal", "outturn_total": pd.NA,
                        "source": "unreadable in the source PDF (row fused with All India); add via aishe_overrides.csv"}])
    df = pd.concat([df, wb], ignore_index=True)
    overrides = get_settings().reference_data_dir / "aishe_overrides.csv"
    if overrides.exists():
        ov = pd.read_csv(overrides, comment="#")
        for r in ov.itertuples(index=False):
            df.loc[df["state"] == canonical_state(r.state), ["outturn_total", "source"]] = [int(r.outturn_total), r.source]
    return df


def parse_plfs(pdf_path) -> pd.DataFrame:
    with pdfplumber.open(pdf_path) as pdf:
        text = pdf.pages[PLFS_PAGE - 1].extract_text() or ""
    rows = []
    for line in text.splitlines():
        m = re.match(r"^([A-Za-z][A-Za-z &.]+?)\s+((?:[\d.]+\s*){3,9})$", line.strip())
        if not m or m.group(1).lower().startswith(("state", "all india", "rural")):
            continue
        nums = m.group(2).split()
        rows.append({"state": canonical_state(m.group(1)), "youth_ur_pct": float(nums[-1])})
    df = pd.DataFrame(rows).drop_duplicates("state")
    df["source"] = "PLFS 2023-24 Table 18: UR (%), usual status ps+ss, age 15-29, rural+urban, persons"
    return df


def main() -> int:
    s = get_settings()
    govt = s.external_data_dir / "govt"
    aishe = parse_aishe(govt / "aishe_2021_22.pdf")
    plfs = parse_plfs(govt / "AnnualReport_PLFS2023-24L2.pdf")
    ref = s.reference_data_dir
    header = "# Derived from Government of India publications; see data/SOURCES.md. Generated by ml_pipeline/supply/parse.py.\n"
    for df, name in [(aishe, "aishe_2021_22_state_outturn.csv"), (plfs, "plfs_2023_24_youth_ur.csv")]:
        with open(ref / name, "w", encoding="utf-8", newline="") as f:
            f.write(header)
            df.to_csv(f, index=False)
    print(f"AISHE: {aishe['outturn_total'].notna().sum()} states with out-turn; PLFS: {len(plfs)} states")
    return 0


if __name__ == "__main__":
    sys.exit(main())
